### ISSUE TITLE
SRR CAD + mechanical + electrical mounting

### ISSUE THREAD

**Issue by Dat-Bois** [InspirationRobotics/RobotX2024#1]
- [ ] SRR Mount
 - [ ] SRR Solder
 - [ ] SRR (connect with Teensy or with Jetson for T500 control)

**Comment by colin-szeto** [comment]
CABLE OD 0.21''

**Comment by colin-szeto** [comment]
PG9

**Comment by colin-szeto** [comment]
0.135 HOLE SIZE GRIP
