### ISSUE TITLE
Heart beat messaging system

### ISSUE THREAD

**Issue by colin-szeto** [InspirationRobotics/RobotX2024#14]
see the most recent updates to V3 of the handbook

**Comment by Dat-Bois** [comment]
Can you please list the requirements here in bullet points

**Comment by colin-szeto** [comment]
D.3. Heartbeat Message
The AMS is required to transmit a heartbeat status message at exactly a frequency of 1 Hz. This heartbeat is used to verify the link has been established with the Technical Director Network and competition equipment. In addition, this channel is used to relay information specific to a task during its run attempt. The fields for the heartbeat message are shown in Table 12, and followed by an example heartbeat message.

|Name 			|Example 		|Description 					|Notes                                |
|--|--|--|--|
|Message ID 	|$RXHRB 		|Protocol Header				|                               |
|--|--|--|--|
|EST Date		|031124   		|ddmmyy 						|Use U.S. Eastern Standard Time (EST) |
|--|--|--|--|
|EST Time		|161229   		|hhmmss (24hr time format)  	|Use U.S. Eastern Standard Time (EST) |
|--|--|--|--|
|Latitude		|27.37498 		|Decimal degrees 				|Provides ~1.11m accuracy             |
|--|--|--|--|
|N/S indicator	|N 				|N=north, S=South   			|                                     |
|--|--|--|--|
|Longitude 		|82.45100 		|Decimal 						|degrees Provides ~1.04m accuracy     |
|--|--|--|--|
|E/Windicator	|W 				|E=east, W=west     			|                                     |
|--|--|--|--|
| Team ID 		|ROBOT 			|Team ID 5-character code assigned by Technical Director| 				|
|--|--|--|--|
| System Mode	| 2 			|Current mode of AMS 1=Remote Operated 2=Autonomous 3=Killed|			|
|--|--|--|--|
| UAV Status 	|1 				|Current UAV Status 1=Stowed 2=Deployed 3=Faulted | The ‘Stowed’ state used only when the UAV is secured to the USV. The ‘Deployed’ state is used whenever the UAV is not on board the USV. The ‘Faulted’ state is used whenever the UAV is not functioning as designed.|
|--|--|--|--|
| Checksum 		|24 			|Bitwise XOR    				 |                						`|
|--|--|--|--|
| <CR><LF> 		|End of message |    							 |                						`|


Heartbeat Example Message: $RXHRB,031124,161229,27.37498,N,82.45100,W,ROBOT,2,1*24

**Comment by Dat-Bois** [comment]
Status: 

Finished on boat side need to implement ground station script to receive the heartbeat (Should not be too bad).
