### ISSUE TITLE
Technical Paper draft 1

### ISSUE THREAD

**Issue by mabeltree** [InspirationRobotics/RobotX2024#3]
write first draft of all sections of the technical paper - does not have to be polished if it is hard to write use speech to voice and just say what you worked on this year.

**Comment by colin-szeto** [comment]
https://docs.google.com/document/d/1uDeLpNXmvDT_7oeL0x8DFuQ9jSRPvaBd6UaVRzUMd7w/edit


^ notes


draft: 

https://docs.google.com/document/d/1eh_wNDtii4uJJROITt8C59Vf7D9yBADFRkx_RPxe_PU/edit
