### ISSUE TITLE
FVT board replacement mount, + interfacing with fans

### ISSUE THREAD

**Issue by Dat-Bois** [InspirationRobotics/RobotX2024#6]
In case the power regulator board doesn't work, design mounts for just the ESCs with fan mounts and wire routing to junction boxes for the motors.

- [x] cad the board
- [x] 3D print 
- [ ] cut the cables 
- [x] route the cables 
- [ ]

**Comment by colin-szeto** [comment]
need to expand to 4 esc mount

**Comment by colin-szeto** [comment]
- [ ] test replacmeent esc hoepfully not in pre production software
